// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _3Ecommerce.Server.DAL;

#nullable disable

namespace _3Ecommerce.Server.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20230308054603_inicial")]
    partial class inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("_3Ecommerce.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "V8 huge dodge car, Cesar´s fav",
                            ImageUrl = "https://ag-spots-2021.o.auroraobjects.eu/2021/07/04/dodge-charger-srt-hellcat-widebody-c883704072021053710_5.jpg?1625369847",
                            Price = 890000.99m,
                            Title = "Dodge Charger SRT HellCat WideBody 2021"
                        },
                        new
                        {
                            Id = 2,
                            Description = "V10 Wide Agressive car, Like a Vin Diesel actor Fav car",
                            ImageUrl = "https://ag-spots-2021.o.auroraobjects.eu/2021/03/03/dodge-challenger-srt-hellcat-widebody-2019-c277503032021013737_3.jpg",
                            Price = 57000.99m,
                            Title = "Dodge Charger SRT HellCat WideBody 2021"
                        },
                        new
                        {
                            Id = 3,
                            Description = " T-Rex that eating RAPTORS becomes a truck, our Daddy´s Really like this",
                            ImageUrl = "https://lifestyleautogroup.ca/wp-content/uploads/2022/04/TRX-03-scaled.jpg",
                            Price = 120000.99m,
                            Title = "2022 Dodge RAM TRX"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
